In [2]:
%matplotlib inline
import pandas as pd
import dask.dataframe as dd
from dask_ml.preprocessing import DummyEncoder
import numpy as np
import altair as alt
import seaborn as sns
import math

from mpl_toolkits.mplot3d import Axes3D
from matplotlib import pyplot as plt

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, roc_auc_score
from sklearn import metrics

from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.linear_model import LinearRegression
from sklearn import svm
from sklearn.neural_network import MLPClassifier

import random

plt.style.use('ggplot')

# The Perceptron

Based on a simple (the simplest) nerual net.

![http://i.stack.imgur.com/KUvpQ.png](http://i.stack.imgur.com/KUvpQ.png)


$h(x) = sign((\sum{w_ix_i}) - threshold)$

Can simplify by adding an artificial coordinate $x_0$ and $w_0$  where $x_0 = 1$ 

This makes it easy

$h(x) = sign(\sum{w_ix_i})$

or in vector notation

$h(x) = sign(w \cdot x)$



## So, how is this a learning system?

We need a learning algorithm

Supervised Learning requires a training set where we have some data and we know the answer.

1. Given a training set of $\vec x,\vec y$
2. Classify all of the points in $\vec x$
3. Pick a point $n$ from $\vec x$ that was misclassified
4. update the weight vector $\vec w$ using: $\vec w = \vec w + y_n \vec x$

Repeat 2 -- 4 until all points are classified correctly.  OR at some upper limit of iteration.


#### The McCulloch and Pitts neuron is a binary threshold device. It sums up the inputs (multiplied by the synaptic strengths or weights) and either fires (produces output 1) or does not fire (produces output 0) depending on whether the input is above some threshold.

## numpy tidbits

#### making an array of randomly generated numbers between 0 and 1

In [3]:
np.array([random.random() for x in range(2)])

array([0.09088202, 0.20334489])

In [4]:
np.array([2, 3, 4])

array([2, 3, 4])

#### inserting number into index 0 of a list

In [5]:
ii = [(1, 2), (4, 7), (9, 4), (5, 3)]
np.c_[np.array([1.0]*len(ii)), ii]    

array([[1., 1., 2.],
       [1., 4., 7.],
       [1., 9., 4.],
       [1., 5., 3.]])

In [68]:
asdf = [(4, 1), (4, 10), (3, 5),]

np.c_[[1.0]*len(asdf), asdf]

array([[ 1.,  4.,  1.],
       [ 1.,  4., 10.],
       [ 1.,  3.,  5.]])

#### array of just zeros

In [7]:
np.zeros(3)

array([0., 0., 0.])

#### regular lists concatenate, numpy arrays add its contents together to from new numbers

In [9]:
# regular lists concaten
e = [1,2,3]
f = [5,6,7]
f = e + f
print(f)

[1, 2, 3, 5, 6, 7]


In [10]:
# np arrays
p = np.array([1, 2, 3])
c = np.array([1, 1, 1])
# print(p, c)
print(p + c)

[2 3 4]


#### The sign function returns -1 if x < 0, 0 if x==0, 1 if x > 0. nan is returned for nan inputs

In [11]:
print(np.sign(-32))
print(np.sign(0))
print(np.sign(8))
print(np.nan)

-1
0
1
nan


#### np.dot does a product of two arrays

In [13]:
np.dot([1,2,3], [1.124, .003, .167])

1.6310000000000002

#### enumerate() returns a tuple

In [15]:
bb = ['hellow', 'world']
print(list(enumerate(bb))) # I turned it into a list in order to get a readable print statement, otherwise the enumerate 
                           # object would have been returned

[(0, 'hellow'), (1, 'world')]


#### misc

In [16]:
print(np.array([1, 3, 7])*[-1])
print([1, 3, 7]*-1)

[-1 -3 -7]
[]


## taking a look at the fit method outside of the Perceptron class

In [70]:
def addBias(data):
    return np.c_[[1.0]*len(data), data]

x = addBias(pts)
w = np.array([random.random() for x in range(len(x[0]))])
# print(x)
# print('~~~~~~~~~~~~~~~~~~~~~~')
# 0, (1, 4, 1)
for ix,i in enumerate(x):
    print("ix: ", ix)
    print("i: ", i)
    print("np.sign(np.dot(i, w)): ", np.sign(np.dot(i, w)))
    print("y[ix]: ", y[ix])
    if np.sign(np.dot(i, w)) != y[ix]:
#         print("w before: ", w)
#         print("w = " + str(w) + " + " + str(i) + "*" + str(y) + "[" + str(ix) + "]")
        w = w + i*y[ix]
#         print("w after: ", w)

ix:  0
i:  [1. 4. 1.]
np.sign(np.dot(i, w)):  1.0
y[ix]:  0
ix:  1
i:  [ 1.  4. 10.]
np.sign(np.dot(i, w)):  1.0
y[ix]:  0
ix:  2
i:  [1. 3. 5.]
np.sign(np.dot(i, w)):  1.0
y[ix]:  0
ix:  3
i:  [1. 4. 4.]
np.sign(np.dot(i, w)):  1.0
y[ix]:  0
ix:  4
i:  [ 1.  8. 10.]
np.sign(np.dot(i, w)):  1.0
y[ix]:  0
ix:  5
i:  [1. 6. 9.]
np.sign(np.dot(i, w)):  1.0
y[ix]:  0
ix:  6
i:  [ 1.  7. 11.]
np.sign(np.dot(i, w)):  1.0
y[ix]:  0
ix:  7
i:  [1. 5. 7.]
np.sign(np.dot(i, w)):  1.0
y[ix]:  0
ix:  8
i:  [1. 4. 2.]
np.sign(np.dot(i, w)):  1.0
y[ix]:  0
ix:  9
i:  [1. 2. 3.]
np.sign(np.dot(i, w)):  1.0
y[ix]:  0
ix:  10
i:  [1. 7. 6.]
np.sign(np.dot(i, w)):  1.0
y[ix]:  0


In [17]:
#Some sample data
pts = [(4, 1),
 (4, 10),
 (3, 5),
 (4, 4),
 (8, 10),
 (6, 9),
 (7, 11),
 (5, 7),
 (4, 2),
 (2, 3),
 (7, 6)
      ]

y = [-1, 1, -1, -1, 1, 1, 1, 1, -1, -1, 1]

In [64]:
class Perceptron:
    def __init__(self):
        self.w = []
    
    def fit(self, x, y):
        self.x = x
        self.y = y
        
        # insert a bias of 1 into each row in x
        self.x = self.addBias(self.x)
        
        # num of weights is equal to items per row in x + bias
        self.w = np.array([random.random() for x in range(len(self.x[0]))])
        
        for i in range(1000):
            # ix, i --> 0, (1, 4, 1)
            for ix,j in enumerate(self.x):
                # np.dot multiplies the row and weights, np.sign returns 1 if > 0 else 0, check if not equal 
                    # to self.y[ix]
#                 print("j: ", j)
#                 print("ix: ", ix)
#                 print("y[ix]: ", self.y[ix])
#                 print("self.w: ", self.w)
#                 print("np.dot(i, self.w): ", np.dot(i, self.w))
#                 print("np.sign(np.dot(i, self.w)): ", np.sign(np.dot(i, self.w)))
#                 print("self.y[ix]: ", self.y[ix])
                if np.sign(np.dot(j, self.w)) != self.y[ix]:
#                     ex: [0.8417449  0.92459656 0.75276383] + [1. 4. 1.]*[-1, 1, -1, -1, 1, 1, 1, 1, -1, -1, 1][0]
#                     because these two arrays are np objects, they will add together 
#                         NOT concatenate like regular arrays
                    self.w = self.w + j*self.y[ix] # update the weights
#                 print('~~~~')
                                
    def addBias(self, data):
        return np.c_[[1.0]*len(data), data]
    
    def predict(self, test):
        test = self.addBias(test)
#         print(test)
#         print("in predict row: ", row)
        predictions = []
        for pt in test:
            predictions.append(np.sign(np.dot(pt, self.w)))
        return predictions
    
    def getWeights(self):
        return self.w


# CLASS NOTES
# initial weights are randomly chosen between -1 and 1
# make sure to add a bias column of 1
# once you have dot prod, pass through sign function, if sum of product is > 0, its 1, else 0

In [19]:
train = pd.DataFrame(pts).values
# train

In [20]:
np.array([np.array([1,1]), np.array([8,8])])

array([[1, 1],
       [8, 8]])

In [30]:
# misc 
# percept.predict(np.array([np.array([1,1]), np.array([8,8])], ndmin=2))

# Iris data with Perceptron class

In [38]:
iris = pd.read_csv('Data/iris.csv')
iris.head()

sepal_length  sepal_width  petal_length  petal_width         name
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [39]:
# label encode iris data
irisencode = iris
labelencoder = LabelEncoder()
irisencode['name'] = labelencoder.fit_transform(irisencode['name'])
irisencode.head()

sepal_length  sepal_width  petal_length  petal_width  name
0           5.1          3.5           1.4          0.2     0
1           4.9          3.0           1.4          0.2     0
2           4.7          3.2           1.3          0.2     0
3           4.6          3.1           1.5          0.2     0
4           5.0          3.6           1.4          0.2     0

In [60]:
X = irisencode.iloc[:, 0:3] 
y = irisencode.iloc[:, 4]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [66]:
percept = Perceptron()
percept.fit(X_train.values, y_train.values)
percpt_pred = percept.predict(X_test)

In [71]:
accuracy_score(y_test, percpt_pred) # poor accuracy score because the Perceptron is not build to handle multi-class classification

0.3